# Example ESPHome configuration for lvgl_game_runner component
# This demonstrates how to set up a game runner with Snake game

esphome:
  name: game-runner-demo

esp32:
  variant: esp32
  framework:
    type: esp-idf

# External components
external_components:
  - source:
      type: local
      path: esphome/components
    components: [lvgl_game_runner, game_snake, game_breakout, game_pong, game_platform]

# Display configuration (example with ST7789V)
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23

display:
  - platform: st7789v
    id: main_display
    model: TTGO TDisplay 135x240
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    rotation: 270
    update_interval: never  # LVGL will handle updates

# LVGL configuration
lvgl:
  displays:
    - main_display

  # Define the canvas for game rendering
  pages:
    - id: game_page
      widgets:
        - canvas:
            id: game_canvas
            width: 240
            height: 135
            buffer_size: auto
            bg_color: 0x000000

# Game components (register games with the runner)
game_snake:
  id: snake

game_breakout:
  id: breakout

# Platform game - side-scrolling platformer with multiplayer support
game_platform:
  id: platform
  # Multiplayer settings (up to 4 players)
  num_human_players: 2  # Rest will be AI-controlled

  # Level generation seed - same seed produces same levels
  seed: 42
  level_width_tiles: 64
  level_height_tiles: 16

  # Difficulty settings
  difficulty: normal  # easy, normal, hard, extreme
  ai_difficulty: intermediate  # beginner, intermediate, advanced, expert
  initial_lives: 3

  # Level progression
  enable_hidden_levels: true  # Secret bonus levels
  boss_every_n_levels: 5  # Boss fight frequency

  # Physics tuning
  player_speed: 1.0  # 0.5 to 3.0
  jump_strength: 1.0  # 0.5 to 2.0
  gravity: 1.0  # 0.5 to 2.0

  # Player abilities
  enable_double_jump: false
  enable_wall_jump: false

  # Multiplayer mechanics
  friendly_fire: false  # Teammates can't hurt each other
  shared_lives: false  # All players share a life pool

  # Content density
  max_enemies_per_level: 10
  powerup_frequency: 1.0  # Multiplier for powerup spawn rate

# Game runner configuration
lvgl_game_runner:
  id: snake_game
  initial_game: snake
  canvas: game_canvas
  fps: 30
  start_paused: false

# Input controls - Example with buttons
binary_sensor:
  # D-pad style controls
  - platform: gpio
    id: button_up
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - lvgl_game_runner.send_input:
          id: snake_game
          input: "UP"

  - platform: gpio
    id: button_down
    pin:
      number: GPIO35
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - lvgl_game_runner.send_input:
          id: snake_game
          input: "DOWN"

  - platform: gpio
    id: button_left
    pin:
      number: GPIO34
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - lvgl_game_runner.send_input:
          id: snake_game
          input: "LEFT"

  - platform: gpio
    id: button_right
    pin:
      number: GPIO39
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - lvgl_game_runner.send_input:
          id: snake_game
          input: "RIGHT"

  # Start/restart button
  - platform: gpio
    id: button_start
    pin:
      number: GPIO26
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - lvgl_game_runner.send_input:
          id: snake_game
          input: "START"

  # A button (Jump in platform game)
  - platform: gpio
    id: button_a
    pin:
      number: GPIO27
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - lvgl_game_runner.send_input:
          id: snake_game
          input: "A"
    on_release:
      - lvgl_game_runner.send_input:
          id: snake_game
          input: "A"
          pressed: false

  # B button (Action/Shoot in platform game)
  - platform: gpio
    id: button_b
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - lvgl_game_runner.send_input:
          id: snake_game
          input: "B"

  # Player 2 controls (for multiplayer platform game)
  # Note: player parameter specifies which player (0-3)
  - platform: gpio
    id: p2_button_left
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - lvgl_game_runner.send_input:
          id: snake_game
          input: "LEFT"
          player: 1

  - platform: gpio
    id: p2_button_right
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - lvgl_game_runner.send_input:
          id: snake_game
          input: "RIGHT"
          player: 1

  - platform: gpio
    id: p2_button_jump
    pin:
      number: GPIO15
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - lvgl_game_runner.send_input:
          id: snake_game
          input: "A"
          player: 1

# Alternative: Rotary encoder input
# sensor:
#   - platform: rotary_encoder
#     id: game_knob
#     pin_a: GPIO32
#     pin_b: GPIO33
#     resolution: 1
#     on_clockwise:
#       - lvgl_game_runner.send_input:
#           id: snake_game
#           input: "ROTATE_CW"
#     on_anticlockwise:
#       - lvgl_game_runner.send_input:
#           id: snake_game
#           input: "ROTATE_CCW"

# Example automation: pause/resume
# script:
#   - id: toggle_game
#     then:
#       - lvgl_game_runner.toggle: snake_game
#
#   - id: restart_game
#     then:
#       - lvgl_game_runner.start: snake_game

# Home Assistant integration (optional)
api:
  services:
    - service: start_game
      then:
        - lvgl_game_runner.start: snake_game

    - service: pause_game
      then:
        - lvgl_game_runner.pause: snake_game

    - service: resume_game
      then:
        - lvgl_game_runner.resume: snake_game

    - service: set_game
      variables:
        game_name: string
      then:
        - lvgl_game_runner.set_game:
            id: snake_game
            game: !lambda 'return game_name;'

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG
